workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 45
    scripts:
      - name: Clean
        script: ./gradlew clean
      - name: Build Debug APK
        # gera APK de debug, já assinado com a chave default do Android Studio
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - maisconhe@gmail.com