workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60

    triggering:
      events:
        - push
        - pull_request

    scripts:
      - name: Clean
        script: |
          bash gradlew clean

      - name: Build debug APK
        script: |
          bash gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
